CREATE TABLESPACE GRC_WORKFLOW_DATA
DATAFILE 'GRC_WORKFLOW_data.dat'
SIZE 10M AUTOEXTEND ON;

CREATE TABLESPACE GRC_WORKFLOW_IDX
DATAFILE 'GRC_WORKFLOW_idx.dat'
SIZE 10M AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE GRC_WORKFLOW_DATA_TEMP
TEMPFILE 'GRC_WORKFLOW_data_temp.dat'
SIZE 5M AUTOEXTEND ON;

CREATE USER GRC_WORKFLOW
IDENTIFIED BY GRC_WORKFLOW
DEFAULT TABLESPACE GRC_WORKFLOW_DATA
TEMPORARY TABLESPACE GRC_WORKFLOW_DATA_TEMP;

GRANT CREATE SESSION TO GRC_WORKFLOW;
GRANT CREATE TABLE TO GRC_WORKFLOW;
GRANT CREATE VIEW TO GRC_WORKFLOW;
GRANT UNLIMITED TABLESPACE TO GRC_WORKFLOW;

--------------------------------------------------------
--  DDL for Table BPM_INSTANCE
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table BPM_INSTANCE
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."BPM_INSTANCE" 
   (	"INSTANCEID" VARCHAR2(64 BYTE), 
	"PROCESSID" VARCHAR2(100 BYTE), 
	"PROCESSNAME" VARCHAR2(400 BYTE), 
	"EXECUTIONID" VARCHAR2(200 BYTE), 
	"PARENTINSTANCEID" VARCHAR2(200 BYTE), 
	"CREATEDBY" VARCHAR2(400 BYTE), 
	"UPDATEDBY" VARCHAR2(400 BYTE), 
	"STARTDATE" TIMESTAMP (6), 
	"ENDDATE" TIMESTAMP (6), 
	"STATUS" VARCHAR2(100 BYTE), 
	"WORKORDERID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table BPM_PROCESS
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."BPM_PROCESS" 
   (	"PROCESSID" VARCHAR2(64 BYTE), 
	"PROCESSNAME" VARCHAR2(100 BYTE), 
	"PROJECTNAME" VARCHAR2(100 BYTE), 
	"VERSION" NUMBER(*,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"STATE" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table BPM_SYSTEM_EXCEPTION
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" 
   (	"ID" VARCHAR2(200 BYTE), 
	"INSTANCEID" VARCHAR2(64 BYTE), 
	"TASKID" VARCHAR2(64 BYTE), 
	"PROCESSID" VARCHAR2(100 BYTE), 
	"PROCESSNAME" VARCHAR2(400 BYTE), 
	"EXECUTIONID" VARCHAR2(200 BYTE), 
	"CREATIONDATE" TIMESTAMP (6), 
	"ERRORMESSAGE" VARCHAR2(1000 BYTE), 
	"ERRORCODE" VARCHAR2(64 BYTE), 
	"FAULTNAME" VARCHAR2(400 BYTE), 
	"FAULTTYPE" VARCHAR2(400 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table BPM_TASK
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."BPM_TASK" 
   (	"TASKID" VARCHAR2(64 BYTE), 
	"TASKNAME" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(500 BYTE), 
	"ACTIVITYNAME" VARCHAR2(200 BYTE), 
	"INSTANCEID" VARCHAR2(64 BYTE), 
	"PROCESSID" VARCHAR2(100 BYTE), 
	"PROCESSNAME" VARCHAR2(400 BYTE), 
	"EXECUTIONID" VARCHAR2(200 BYTE), 
	"ACQUIREDBY" VARCHAR2(400 BYTE), 
	"ASSIGNEES" VARCHAR2(400 BYTE), 
	"REVIEWERS" VARCHAR2(400 BYTE), 
	"ORIGINALASSIGNEEUSER" VARCHAR2(400 BYTE), 
	"CREATOR" VARCHAR2(400 BYTE), 
	"UPDATEDBY" VARCHAR2(400 BYTE), 
	"SWIMLANEROLE" VARCHAR2(200 BYTE), 
	"CREATEDDATE" TIMESTAMP (6), 
	"UPDATEDDATE" TIMESTAMP (6), 
	"DUEDATE" TIMESTAMP (6), 
	"COMPLETEDDATE" TIMESTAMP (6), 
	"CLAIMDATE" TIMESTAMP (6), 
	"PRIORITY" NUMBER, 
	"OUTCOME" VARCHAR2(100 BYTE), 
	"STATE" VARCHAR2(100 BYTE), 
	"TASKTYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table DOCUMENT
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."DOCUMENT" 
   (	"DOCID" VARCHAR2(64 BYTE), 
	"RENDITIONID" VARCHAR2(400 BYTE), 
	"ALERTID" VARCHAR2(100 BYTE), 
	"URL" TIMESTAMP (6), 
	"SOURCEURL" VARCHAR2(400 BYTE), 
	"SOURCEURLID" VARCHAR2(32 BYTE), 
	"TITLE" VARCHAR2(3 BYTE), 
	"CITE" VARCHAR2(400 BYTE), 
	"CITATIONS" VARCHAR2(400 BYTE), 
	"CORRELATIONID" VARCHAR2(3 BYTE), 
	"CONTENTTYPE" VARCHAR2(100 BYTE), 
	"COMPLIANCECOMPLETECONTENTTYPE" VARCHAR2(3 BYTE), 
	"ARTIFACTDESCRIPTORID" VARCHAR2(100 BYTE), 
	"PUBLICATIONDATE" TIMESTAMP (6), 
	"WSID" VARCHAR2(20 BYTE), 
	"WORKORDERID" VARCHAR2(20 BYTE), 
	"DOCTYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table GRC_PAYLOAD
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" 
   (	"GRC_PAYLOAD_ID" VARCHAR2(64 BYTE), 
	"WORKORDERID" VARCHAR2(100 BYTE), 
	"INSTANCEID" VARCHAR2(64 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table WORK_ORDER
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."WORK_ORDER" 
   (	"WORKORDERID" VARCHAR2(64 BYTE), 
	"UUID" VARCHAR2(400 BYTE), 
	"REGARDING" VARCHAR2(100 BYTE), 
	"STARTDATE" TIMESTAMP (6), 
	"SUMMARY" VARCHAR2(400 BYTE), 
	"STATUS" VARCHAR2(32 BYTE), 
	"HASCHANGED" VARCHAR2(3 BYTE), 
	"UPDATEDBY" VARCHAR2(400 BYTE), 
	"UPDATEDBYTOKEN" VARCHAR2(400 BYTE), 
	"ISMANUALWORKORDER" VARCHAR2(3 BYTE), 
	"SECTORSCONCEPTIDS" VARCHAR2(100 BYTE), 
	"WORKPRODUCTTYPE" TIMESTAMP (6), 
	"INSTANCEID" VARCHAR2(20 BYTE), 
	"DOCID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table WORK_STREAM
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."WORK_STREAM" 
   (	"WSID" VARCHAR2(64 BYTE), 
	"UUID" VARCHAR2(400 BYTE), 
	"WORKORDERID" VARCHAR2(100 BYTE), 
	"WORKORDERUUID" TIMESTAMP (6), 
	"WORKPRODUCT" VARCHAR2(400 BYTE), 
	"WORKPRODUCTID" VARCHAR2(32 BYTE), 
	"COUNTRY" VARCHAR2(3 BYTE), 
	"COUNTRYCONCEPTID" VARCHAR2(400 BYTE), 
	"REGION" VARCHAR2(400 BYTE), 
	"REGIONCONCEPTID" VARCHAR2(3 BYTE), 
	"JURISDICTION" VARCHAR2(100 BYTE), 
	"REGULATOR" VARCHAR2(3 BYTE), 
	"SECTOR" VARCHAR2(100 BYTE), 
	"DUEDATE" TIMESTAMP (6), 
	"DOCID" VARCHAR2(20 BYTE), 
	"INSTANCEID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index BPM_INSTANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."BPM_INSTANCE_PK" ON "GRC_WORKFLOW"."BPM_INSTANCE" ("INSTANCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index BPM_PROCESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."BPM_PROCESS_PK" ON "GRC_WORKFLOW"."BPM_PROCESS" ("PROCESSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index BPM_SYSTEM_EXCEPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION_PK" ON "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index BPM_TASK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."BPM_TASK_PK" ON "GRC_WORKFLOW"."BPM_TASK" ("TASKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index DOCUMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."DOCUMENT_PK" ON "GRC_WORKFLOW"."DOCUMENT" ("DOCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index GRC_PAYLOAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."GRC_PAYLOAD_PK" ON "GRC_WORKFLOW"."GRC_PAYLOAD" ("GRC_PAYLOAD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index GRC_PAYLOAD_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."GRC_PAYLOAD_UK1" ON "GRC_WORKFLOW"."GRC_PAYLOAD" ("WORKORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index WORK_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."WORK_ORDER_PK" ON "GRC_WORKFLOW"."WORK_ORDER" ("WORKORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index WORK_STREAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."WORK_STREAM_PK" ON "GRC_WORKFLOW"."WORK_STREAM" ("WSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  Constraints for Table BPM_INSTANCE
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_INSTANCE" ADD CONSTRAINT "BPM_INSTANCE_PK" PRIMARY KEY ("INSTANCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_INSTANCE" MODIFY ("INSTANCEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPM_PROCESS
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_PROCESS" ADD CONSTRAINT "BPM_PROCESS_PK" PRIMARY KEY ("PROCESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_PROCESS" MODIFY ("PROCESSID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPM_SYSTEM_EXCEPTION
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" ADD CONSTRAINT "BPM_SYSTEM_EXCEPTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" MODIFY ("INSTANCEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPM_TASK
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_TASK" ADD CONSTRAINT "BPM_TASK_PK" PRIMARY KEY ("TASKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_TASK" MODIFY ("TASKID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" ADD CONSTRAINT "DOCUMENT_PK" PRIMARY KEY ("DOCID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" MODIFY ("DOCID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" MODIFY ("RENDITIONID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" MODIFY ("WORKORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRC_PAYLOAD
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" ADD CONSTRAINT "GRC_PAYLOAD_PK" PRIMARY KEY ("GRC_PAYLOAD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" ADD CONSTRAINT "GRC_PAYLOAD_UK1" UNIQUE ("WORKORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" MODIFY ("GRC_PAYLOAD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" MODIFY ("WORKORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORK_ORDER
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."WORK_ORDER" MODIFY ("WORKORDERID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."WORK_ORDER" ADD CONSTRAINT "WORK_ORDER_PK" PRIMARY KEY ("WORKORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORK_STREAM
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."WORK_STREAM" MODIFY ("WSID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."WORK_STREAM" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."WORK_STREAM" ADD CONSTRAINT "WORK_STREAM_PK" PRIMARY KEY ("WSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BPM_TASK
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_TASK" ADD CONSTRAINT "BPM_TASK_INSTANCE" FOREIGN KEY ("INSTANCEID")
	  REFERENCES "GRC_WORKFLOW"."BPM_INSTANCE" ("INSTANCEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" ADD CONSTRAINT "DOCUMENT_FK1" FOREIGN KEY ("WORKORDERID")
	  REFERENCES "GRC_WORKFLOW"."WORK_ORDER" ("WORKORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRC_PAYLOAD
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" ADD CONSTRAINT "WO_ID_FK1" FOREIGN KEY ("WORKORDERID")
	  REFERENCES "GRC_WORKFLOW"."WORK_ORDER" ("WORKORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORK_ORDER
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."WORK_ORDER" ADD CONSTRAINT "WORK_ORDER_FK2" FOREIGN KEY ("INSTANCEID")
	  REFERENCES "GRC_WORKFLOW"."BPM_INSTANCE" ("INSTANCEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORK_STREAM
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."WORK_STREAM" ADD CONSTRAINT "WORK_ORDER_FK1" FOREIGN KEY ("WORKORDERID")
	  REFERENCES "GRC_WORKFLOW"."WORK_ORDER" ("WORKORDERID") ENABLE;
