CREATE TABLESPACE GRC_WORKFLOW_DATA
DATAFILE 'GRC_WORKFLOW_data.dat'
SIZE 10M AUTOEXTEND ON;

CREATE TABLESPACE GRC_WORKFLOW_IDX
DATAFILE 'GRC_WORKFLOW_idx.dat'
SIZE 10M AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE GRC_WORKFLOW_DATA_TEMP
TEMPFILE 'GRC_WORKFLOW_data_temp.dat'
SIZE 5M AUTOEXTEND ON;

CREATE USER GRC_WORKFLOW
IDENTIFIED BY GRC_WORKFLOW
DEFAULT TABLESPACE GRC_WORKFLOW_DATA
TEMPORARY TABLESPACE GRC_WORKFLOW_DATA_TEMP;

GRANT CREATE SESSION TO GRC_WORKFLOW;
GRANT CREATE TABLE TO GRC_WORKFLOW;
GRANT CREATE VIEW TO GRC_WORKFLOW;
GRANT UNLIMITED TABLESPACE TO GRC_WORKFLOW;

--------------------------------------------------------
--  DDL for Table BPM_INSTANCE
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table BPM_INSTANCE
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."BPM_INSTANCE" 
   (	"INSTANCEID" VARCHAR2(64 BYTE), 
	"PROCESSID" VARCHAR2(100 BYTE), 
	"PROCESSNAME" VARCHAR2(400 BYTE), 
	"EXECUTIONID" VARCHAR2(200 BYTE), 
	"PARENTINSTANCEID" VARCHAR2(200 BYTE), 
	"CREATEDBY" VARCHAR2(400 BYTE), 
	"UPDATEDBY" VARCHAR2(400 BYTE), 
	"STARTDATE" TIMESTAMP (6), 
	"ENDDATE" TIMESTAMP (6), 
	"STATUS" VARCHAR2(100 BYTE), 
	"WORKORDERID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table BPM_PROCESS
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."BPM_PROCESS" 
   (	"PROCESSID" VARCHAR2(64 BYTE), 
	"PROCESSNAME" VARCHAR2(100 BYTE), 
	"PROJECTNAME" VARCHAR2(100 BYTE), 
	"VERSION" NUMBER(*,0), 
	"CREATEDDATE" TIMESTAMP (6), 
	"STATE" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table BPM_SYSTEM_EXCEPTION
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" 
   (	"ID" VARCHAR2(200 BYTE), 
	"INSTANCEID" VARCHAR2(64 BYTE), 
	"TASKID" VARCHAR2(64 BYTE), 
	"PROCESSID" VARCHAR2(100 BYTE), 
	"PROCESSNAME" VARCHAR2(400 BYTE), 
	"EXECUTIONID" VARCHAR2(200 BYTE), 
	"CREATIONDATE" TIMESTAMP (6), 
	"ERRORMESSAGE" VARCHAR2(1000 BYTE), 
	"ERRORCODE" VARCHAR2(64 BYTE), 
	"FAULTNAME" VARCHAR2(400 BYTE), 
	"FAULTTYPE" VARCHAR2(400 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table BPM_TASK
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."BPM_TASK" 
   (	"TASKID" VARCHAR2(64 BYTE), 
	"TASKNAME" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(500 BYTE), 
	"ACTIVITYNAME" VARCHAR2(200 BYTE), 
	"INSTANCEID" VARCHAR2(64 BYTE), 
	"PROCESSID" VARCHAR2(100 BYTE), 
	"PROCESSNAME" VARCHAR2(400 BYTE), 
	"EXECUTIONID" VARCHAR2(200 BYTE), 
	"ACQUIREDBY" VARCHAR2(400 BYTE), 
	"ASSIGNEES" VARCHAR2(400 BYTE), 
	"REVIEWERS" VARCHAR2(400 BYTE), 
	"ORIGINALASSIGNEEUSER" VARCHAR2(400 BYTE), 
	"CREATOR" VARCHAR2(400 BYTE), 
	"UPDATEDBY" VARCHAR2(400 BYTE), 
	"SWIMLANEROLE" VARCHAR2(200 BYTE), 
	"CREATEDDATE" TIMESTAMP (6), 
	"UPDATEDDATE" TIMESTAMP (6), 
	"DUEDATE" TIMESTAMP (6), 
	"COMPLETEDDATE" TIMESTAMP (6), 
	"CLAIMDATE" TIMESTAMP (6), 
	"PRIORITY" NUMBER, 
	"OUTCOME" VARCHAR2(100 BYTE), 
	"STATE" VARCHAR2(100 BYTE), 
	"TASKTYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table DOCUMENT
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."DOCUMENT" 
   (	"DOCID" VARCHAR2(64 BYTE), 
	"RENDITIONID" VARCHAR2(400 BYTE), 
	"ALERTID" VARCHAR2(100 BYTE), 
	"URL" TIMESTAMP (6), 
	"SOURCEURL" VARCHAR2(400 BYTE), 
	"SOURCEURLID" VARCHAR2(32 BYTE), 
	"TITLE" VARCHAR2(3 BYTE), 
	"CITE" VARCHAR2(400 BYTE), 
	"CITATIONS" VARCHAR2(400 BYTE), 
	"CORRELATIONID" VARCHAR2(3 BYTE), 
	"CONTENTTYPE" VARCHAR2(100 BYTE), 
	"COMPLIANCECOMPLETECONTENTTYPE" VARCHAR2(3 BYTE), 
	"ARTIFACTDESCRIPTORID" VARCHAR2(100 BYTE), 
	"PUBLICATIONDATE" TIMESTAMP (6), 
	"WSID" VARCHAR2(20 BYTE), 
	"WORKORDERID" VARCHAR2(20 BYTE), 
	"DOCTYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table GRC_PAYLOAD
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" 
   (	"GRC_PAYLOAD_ID" VARCHAR2(64 BYTE), 
	"WORKORDERID" VARCHAR2(100 BYTE), 
	"INSTANCEID" VARCHAR2(64 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table WORK_ORDER
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."WORK_ORDER" 
   (	"WORKORDERID" VARCHAR2(64 BYTE), 
	"UUID" VARCHAR2(400 BYTE), 
	"REGARDING" VARCHAR2(100 BYTE), 
	"STARTDATE" TIMESTAMP (6), 
	"SUMMARY" VARCHAR2(400 BYTE), 
	"STATUS" VARCHAR2(32 BYTE), 
	"HASCHANGED" VARCHAR2(3 BYTE), 
	"UPDATEDBY" VARCHAR2(400 BYTE), 
	"UPDATEDBYTOKEN" VARCHAR2(400 BYTE), 
	"ISMANUALWORKORDER" VARCHAR2(3 BYTE), 
	"SECTORSCONCEPTIDS" VARCHAR2(100 BYTE), 
	"WORKPRODUCTTYPE" TIMESTAMP (6), 
	"INSTANCEID" VARCHAR2(20 BYTE), 
	"DOCID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table WORK_STREAM
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."WORK_STREAM" 
   (	"WSID" VARCHAR2(64 BYTE), 
	"UUID" VARCHAR2(400 BYTE), 
	"WORKORDERID" VARCHAR2(100 BYTE), 
	"WORKORDERUUID" TIMESTAMP (6), 
	"WORKPRODUCT" VARCHAR2(400 BYTE), 
	"WORKPRODUCTID" VARCHAR2(32 BYTE), 
	"COUNTRY" VARCHAR2(3 BYTE), 
	"COUNTRYCONCEPTID" VARCHAR2(400 BYTE), 
	"REGION" VARCHAR2(400 BYTE), 
	"REGIONCONCEPTID" VARCHAR2(3 BYTE), 
	"JURISDICTION" VARCHAR2(100 BYTE), 
	"REGULATOR" VARCHAR2(3 BYTE), 
	"SECTOR" VARCHAR2(100 BYTE), 
	"DUEDATE" TIMESTAMP (6), 
	"DOCID" VARCHAR2(20 BYTE), 
	"INSTANCEID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index BPM_INSTANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."BPM_INSTANCE_PK" ON "GRC_WORKFLOW"."BPM_INSTANCE" ("INSTANCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index BPM_PROCESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."BPM_PROCESS_PK" ON "GRC_WORKFLOW"."BPM_PROCESS" ("PROCESSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index BPM_SYSTEM_EXCEPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION_PK" ON "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index BPM_TASK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."BPM_TASK_PK" ON "GRC_WORKFLOW"."BPM_TASK" ("TASKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index DOCUMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."DOCUMENT_PK" ON "GRC_WORKFLOW"."DOCUMENT" ("DOCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index GRC_PAYLOAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."GRC_PAYLOAD_PK" ON "GRC_WORKFLOW"."GRC_PAYLOAD" ("GRC_PAYLOAD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index GRC_PAYLOAD_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."GRC_PAYLOAD_UK1" ON "GRC_WORKFLOW"."GRC_PAYLOAD" ("WORKORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index WORK_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."WORK_ORDER_PK" ON "GRC_WORKFLOW"."WORK_ORDER" ("WORKORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index WORK_STREAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."WORK_STREAM_PK" ON "GRC_WORKFLOW"."WORK_STREAM" ("WSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  Constraints for Table BPM_INSTANCE
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_INSTANCE" ADD CONSTRAINT "BPM_INSTANCE_PK" PRIMARY KEY ("INSTANCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_INSTANCE" MODIFY ("INSTANCEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPM_PROCESS
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_PROCESS" ADD CONSTRAINT "BPM_PROCESS_PK" PRIMARY KEY ("PROCESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_PROCESS" MODIFY ("PROCESSID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPM_SYSTEM_EXCEPTION
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" ADD CONSTRAINT "BPM_SYSTEM_EXCEPTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_SYSTEM_EXCEPTION" MODIFY ("INSTANCEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPM_TASK
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_TASK" ADD CONSTRAINT "BPM_TASK_PK" PRIMARY KEY ("TASKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."BPM_TASK" MODIFY ("TASKID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" ADD CONSTRAINT "DOCUMENT_PK" PRIMARY KEY ("DOCID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" MODIFY ("DOCID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" MODIFY ("RENDITIONID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" MODIFY ("WORKORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRC_PAYLOAD
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" ADD CONSTRAINT "GRC_PAYLOAD_PK" PRIMARY KEY ("GRC_PAYLOAD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" ADD CONSTRAINT "GRC_PAYLOAD_UK1" UNIQUE ("WORKORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" MODIFY ("GRC_PAYLOAD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" MODIFY ("WORKORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORK_ORDER
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."WORK_ORDER" MODIFY ("WORKORDERID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."WORK_ORDER" ADD CONSTRAINT "WORK_ORDER_PK" PRIMARY KEY ("WORKORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORK_STREAM
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."WORK_STREAM" MODIFY ("WSID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."WORK_STREAM" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."WORK_STREAM" ADD CONSTRAINT "WORK_STREAM_PK" PRIMARY KEY ("WSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BPM_TASK
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."BPM_TASK" ADD CONSTRAINT "BPM_TASK_INSTANCE" FOREIGN KEY ("INSTANCEID")
	  REFERENCES "GRC_WORKFLOW"."BPM_INSTANCE" ("INSTANCEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."DOCUMENT" ADD CONSTRAINT "DOCUMENT_FK1" FOREIGN KEY ("WORKORDERID")
	  REFERENCES "GRC_WORKFLOW"."WORK_ORDER" ("WORKORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRC_PAYLOAD
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."GRC_PAYLOAD" ADD CONSTRAINT "WO_ID_FK1" FOREIGN KEY ("WORKORDERID")
	  REFERENCES "GRC_WORKFLOW"."WORK_ORDER" ("WORKORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORK_ORDER
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."WORK_ORDER" ADD CONSTRAINT "WORK_ORDER_FK2" FOREIGN KEY ("INSTANCEID")
	  REFERENCES "GRC_WORKFLOW"."BPM_INSTANCE" ("INSTANCEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORK_STREAM
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."WORK_STREAM" ADD CONSTRAINT "WORK_ORDER_FK1" FOREIGN KEY ("WORKORDERID")
	  REFERENCES "GRC_WORKFLOW"."WORK_ORDER" ("WORKORDERID") ENABLE;

	
--------------------------------------------------------
	  ACTIVITI TABLES
--------------------------------------------------------	

	  --------------------------------------------------------
--  DDL for Table ACT_EVT_LOG
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_EVT_LOG" 
   (    "LOG_NR_" NUMBER(19,0), 
    "TYPE_" NVARCHAR2(64), 
    "PROC_DEF_ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "EXECUTION_ID_" NVARCHAR2(64), 
    "TASK_ID_" NVARCHAR2(64), 
    "TIME_STAMP_" TIMESTAMP (6), 
    "USER_ID_" NVARCHAR2(255), 
    "DATA_" BLOB, 
    "LOCK_OWNER_" NVARCHAR2(255), 
    "LOCK_TIME_" TIMESTAMP (6), 
    "IS_PROCESSED_" NUMBER(3,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" 
 LOB ("DATA_") STORE AS (
  TABLESPACE "GRC_WORKFLOW_DATA" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ACT_RU_TASK
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_RU_TASK" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "EXECUTION_ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "PROC_DEF_ID_" NVARCHAR2(64), 
    "NAME_" NVARCHAR2(255), 
    "PARENT_TASK_ID_" NVARCHAR2(64), 
    "DESCRIPTION_" NVARCHAR2(2000), 
    "TASK_DEF_KEY_" NVARCHAR2(255), 
    "OWNER_" NVARCHAR2(255), 
    "ASSIGNEE_" NVARCHAR2(255), 
    "DELEGATION_" NVARCHAR2(64), 
    "PRIORITY_" NUMBER(*,0), 
    "CREATE_TIME_" TIMESTAMP (6), 
    "DUE_DATE_" TIMESTAMP (6), 
    "CATEGORY_" NVARCHAR2(255), 
    "SUSPENSION_STATE_" NUMBER(*,0), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT '', 
    "FORM_KEY_" NVARCHAR2(255)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_RU_JOB
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_RU_JOB" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "TYPE_" NVARCHAR2(255), 
    "LOCK_EXP_TIME_" TIMESTAMP (6), 
    "LOCK_OWNER_" NVARCHAR2(255), 
    "EXCLUSIVE_" NUMBER(1,0), 
    "EXECUTION_ID_" NVARCHAR2(64), 
    "PROCESS_INSTANCE_ID_" NVARCHAR2(64), 
    "PROC_DEF_ID_" NVARCHAR2(64), 
    "RETRIES_" NUMBER(*,0), 
    "EXCEPTION_STACK_ID_" NVARCHAR2(64), 
    "EXCEPTION_MSG_" NVARCHAR2(2000), 
    "DUEDATE_" TIMESTAMP (6), 
    "REPEAT_" NVARCHAR2(255), 
    "HANDLER_TYPE_" NVARCHAR2(255), 
    "HANDLER_CFG_" NVARCHAR2(2000), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT ''
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_ID_MEMBERSHIP
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_ID_MEMBERSHIP" 
   (    "USER_ID_" NVARCHAR2(64), 
    "GROUP_ID_" NVARCHAR2(64)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_RU_EXECUTION
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "BUSINESS_KEY_" NVARCHAR2(255), 
    "PARENT_ID_" NVARCHAR2(64), 
    "PROC_DEF_ID_" NVARCHAR2(64), 
    "SUPER_EXEC_" NVARCHAR2(64), 
    "ACT_ID_" NVARCHAR2(255), 
    "IS_ACTIVE_" NUMBER(1,0), 
    "IS_CONCURRENT_" NUMBER(1,0), 
    "IS_SCOPE_" NUMBER(1,0), 
    "IS_EVENT_SCOPE_" NUMBER(1,0), 
    "SUSPENSION_STATE_" NUMBER(*,0), 
    "CACHED_ENT_STATE_" NUMBER(*,0), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT '', 
    "NAME_" NVARCHAR2(255), 
    "LOCK_TIME_" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_RE_DEPLOYMENT
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_RE_DEPLOYMENT" 
   (    "ID_" NVARCHAR2(64), 
    "NAME_" NVARCHAR2(255), 
    "CATEGORY_" NVARCHAR2(255), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT '', 
    "DEPLOY_TIME_" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_ID_USER
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_ID_USER" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "FIRST_" NVARCHAR2(255), 
    "LAST_" NVARCHAR2(255), 
    "EMAIL_" NVARCHAR2(255), 
    "PWD_" NVARCHAR2(255), 
    "PICTURE_ID_" NVARCHAR2(64)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_HI_ACTINST
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_HI_ACTINST" 
   (    "ID_" NVARCHAR2(64), 
    "PROC_DEF_ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "EXECUTION_ID_" NVARCHAR2(64), 
    "ACT_ID_" NVARCHAR2(255), 
    "TASK_ID_" NVARCHAR2(64), 
    "CALL_PROC_INST_ID_" NVARCHAR2(64), 
    "ACT_NAME_" NVARCHAR2(255), 
    "ACT_TYPE_" NVARCHAR2(255), 
    "ASSIGNEE_" NVARCHAR2(255), 
    "START_TIME_" TIMESTAMP (6), 
    "END_TIME_" TIMESTAMP (6), 
    "DURATION_" NUMBER(19,0), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT ''
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_PROCDEF_INFO
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_PROCDEF_INFO" 
   (    "ID_" NVARCHAR2(64), 
    "PROC_DEF_ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "INFO_JSON_ID_" NVARCHAR2(64)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_ID_INFO
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_ID_INFO" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "USER_ID_" NVARCHAR2(64), 
    "TYPE_" NVARCHAR2(64), 
    "KEY_" NVARCHAR2(255), 
    "VALUE_" NVARCHAR2(255), 
    "PASSWORD_" BLOB, 
    "PARENT_ID_" NVARCHAR2(255)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" 
 LOB ("PASSWORD_") STORE AS (
  TABLESPACE "GRC_WORKFLOW_DATA" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ACT_RU_EVENT_SUBSCR
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_RU_EVENT_SUBSCR" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "EVENT_TYPE_" NVARCHAR2(255), 
    "EVENT_NAME_" NVARCHAR2(255), 
    "EXECUTION_ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "ACTIVITY_ID_" NVARCHAR2(64), 
    "CONFIGURATION_" NVARCHAR2(255), 
    "CREATED_" TIMESTAMP (6), 
    "PROC_DEF_ID_" NVARCHAR2(64), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT ''
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_HI_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_HI_ATTACHMENT" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "USER_ID_" NVARCHAR2(255), 
    "NAME_" NVARCHAR2(255), 
    "DESCRIPTION_" NVARCHAR2(2000), 
    "TYPE_" NVARCHAR2(255), 
    "TASK_ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "URL_" NVARCHAR2(2000), 
    "CONTENT_ID_" NVARCHAR2(64), 
    "TIME_" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_HI_PROCINST
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_HI_PROCINST" 
   (    "ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "BUSINESS_KEY_" NVARCHAR2(255), 
    "PROC_DEF_ID_" NVARCHAR2(64), 
    "START_TIME_" TIMESTAMP (6), 
    "END_TIME_" TIMESTAMP (6), 
    "DURATION_" NUMBER(19,0), 
    "START_USER_ID_" NVARCHAR2(255), 
    "START_ACT_ID_" NVARCHAR2(255), 
    "END_ACT_ID_" NVARCHAR2(255), 
    "SUPER_PROCESS_INSTANCE_ID_" NVARCHAR2(64), 
    "DELETE_REASON_" NVARCHAR2(2000), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT '', 
    "NAME_" NVARCHAR2(255)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_HI_DETAIL
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_HI_DETAIL" 
   (    "ID_" NVARCHAR2(64), 
    "TYPE_" NVARCHAR2(255), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "EXECUTION_ID_" NVARCHAR2(64), 
    "TASK_ID_" NVARCHAR2(64), 
    "ACT_INST_ID_" NVARCHAR2(64), 
    "NAME_" NVARCHAR2(255), 
    "VAR_TYPE_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "TIME_" TIMESTAMP (6), 
    "BYTEARRAY_ID_" NVARCHAR2(64), 
    "DOUBLE_" NUMBER(*,10), 
    "LONG_" NUMBER(19,0), 
    "TEXT_" NVARCHAR2(2000), 
    "TEXT2_" NVARCHAR2(2000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_RU_IDENTITYLINK
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "GROUP_ID_" NVARCHAR2(255), 
    "TYPE_" NVARCHAR2(255), 
    "USER_ID_" NVARCHAR2(255), 
    "TASK_ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "PROC_DEF_ID_" NVARCHAR2(64)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_GE_BYTEARRAY
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "NAME_" NVARCHAR2(255), 
    "DEPLOYMENT_ID_" NVARCHAR2(64), 
    "BYTES_" BLOB, 
    "GENERATED_" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" 
 LOB ("BYTES_") STORE AS (
  TABLESPACE "GRC_WORKFLOW_DATA" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ACT_HI_IDENTITYLINK
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_HI_IDENTITYLINK" 
   (    "ID_" NVARCHAR2(64), 
    "GROUP_ID_" NVARCHAR2(255), 
    "TYPE_" NVARCHAR2(255), 
    "USER_ID_" NVARCHAR2(255), 
    "TASK_ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_RU_VARIABLE
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_RU_VARIABLE" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "TYPE_" NVARCHAR2(255), 
    "NAME_" NVARCHAR2(255), 
    "EXECUTION_ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "TASK_ID_" NVARCHAR2(64), 
    "BYTEARRAY_ID_" NVARCHAR2(64), 
    "DOUBLE_" NUMBER(*,10), 
    "LONG_" NUMBER(19,0), 
    "TEXT_" NVARCHAR2(2000), 
    "TEXT2_" NVARCHAR2(2000)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_RE_PROCDEF
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_RE_PROCDEF" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "CATEGORY_" NVARCHAR2(255), 
    "NAME_" NVARCHAR2(255), 
    "KEY_" NVARCHAR2(255), 
    "VERSION_" NUMBER(*,0), 
    "DEPLOYMENT_ID_" NVARCHAR2(64), 
    "RESOURCE_NAME_" NVARCHAR2(2000), 
    "DGRM_RESOURCE_NAME_" VARCHAR2(4000 BYTE), 
    "DESCRIPTION_" NVARCHAR2(2000), 
    "HAS_START_FORM_KEY_" NUMBER(1,0), 
    "HAS_GRAPHICAL_NOTATION_" NUMBER(1,0), 
    "SUSPENSION_STATE_" NUMBER(*,0), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT ''
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_RE_MODEL
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_RE_MODEL" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "NAME_" NVARCHAR2(255), 
    "KEY_" NVARCHAR2(255), 
    "CATEGORY_" NVARCHAR2(255), 
    "CREATE_TIME_" TIMESTAMP (6), 
    "LAST_UPDATE_TIME_" TIMESTAMP (6), 
    "VERSION_" NUMBER(*,0), 
    "META_INFO_" NVARCHAR2(2000), 
    "DEPLOYMENT_ID_" NVARCHAR2(64), 
    "EDITOR_SOURCE_VALUE_ID_" NVARCHAR2(64), 
    "EDITOR_SOURCE_EXTRA_VALUE_ID_" NVARCHAR2(64), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT ''
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_HI_VARINST
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_HI_VARINST" 
   (    "ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "EXECUTION_ID_" NVARCHAR2(64), 
    "TASK_ID_" NVARCHAR2(64), 
    "NAME_" NVARCHAR2(255), 
    "VAR_TYPE_" NVARCHAR2(100), 
    "REV_" NUMBER(*,0), 
    "BYTEARRAY_ID_" NVARCHAR2(64), 
    "DOUBLE_" NUMBER(*,10), 
    "LONG_" NUMBER(19,0), 
    "TEXT_" NVARCHAR2(2000), 
    "TEXT2_" NVARCHAR2(2000), 
    "CREATE_TIME_" TIMESTAMP (6), 
    "LAST_UPDATED_TIME_" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_HI_COMMENT
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_HI_COMMENT" 
   (    "ID_" NVARCHAR2(64), 
    "TYPE_" NVARCHAR2(255), 
    "TIME_" TIMESTAMP (6), 
    "USER_ID_" NVARCHAR2(255), 
    "TASK_ID_" NVARCHAR2(64), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "ACTION_" NVARCHAR2(255), 
    "MESSAGE_" NVARCHAR2(2000), 
    "FULL_MSG_" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" 
 LOB ("FULL_MSG_") STORE AS (
  TABLESPACE "GRC_WORKFLOW_DATA" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ACT_HI_TASKINST
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_HI_TASKINST" 
   (    "ID_" NVARCHAR2(64), 
    "PROC_DEF_ID_" NVARCHAR2(64), 
    "TASK_DEF_KEY_" NVARCHAR2(255), 
    "PROC_INST_ID_" NVARCHAR2(64), 
    "EXECUTION_ID_" NVARCHAR2(64), 
    "PARENT_TASK_ID_" NVARCHAR2(64), 
    "NAME_" NVARCHAR2(255), 
    "DESCRIPTION_" NVARCHAR2(2000), 
    "OWNER_" NVARCHAR2(255), 
    "ASSIGNEE_" NVARCHAR2(255), 
    "START_TIME_" TIMESTAMP (6), 
    "CLAIM_TIME_" TIMESTAMP (6), 
    "END_TIME_" TIMESTAMP (6), 
    "DURATION_" NUMBER(19,0), 
    "DELETE_REASON_" NVARCHAR2(2000), 
    "PRIORITY_" NUMBER(*,0), 
    "DUE_DATE_" TIMESTAMP (6), 
    "FORM_KEY_" NVARCHAR2(255), 
    "CATEGORY_" NVARCHAR2(255), 
    "TENANT_ID_" NVARCHAR2(255) DEFAULT ''
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_GE_PROPERTY
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_GE_PROPERTY" 
   (    "NAME_" NVARCHAR2(64), 
    "VALUE_" NVARCHAR2(300), 
    "REV_" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Table ACT_ID_GROUP
--------------------------------------------------------

  CREATE TABLE "GRC_WORKFLOW"."ACT_ID_GROUP" 
   (    "ID_" NVARCHAR2(64), 
    "REV_" NUMBER(*,0), 
    "NAME_" NVARCHAR2(255), 
    "TYPE_" NVARCHAR2(255)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004026
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004026" ON "GRC_WORKFLOW"."ACT_EVT_LOG" ("LOG_NR_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_TASK_CREATE
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_TASK_CREATE" ON "GRC_WORKFLOW"."ACT_RU_TASK" ("CREATE_TIME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_TASK_EXEC
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_TASK_EXEC" ON "GRC_WORKFLOW"."ACT_RU_TASK" ("EXECUTION_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_TASK_PROCINST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_TASK_PROCINST" ON "GRC_WORKFLOW"."ACT_RU_TASK" ("PROC_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_TASK_PROCDEF
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_TASK_PROCDEF" ON "GRC_WORKFLOW"."ACT_RU_TASK" ("PROC_DEF_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004015
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004015" ON "GRC_WORKFLOW"."ACT_RU_TASK" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_JOB_EXCEPTION
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_JOB_EXCEPTION" ON "GRC_WORKFLOW"."ACT_RU_JOB" ("EXCEPTION_STACK_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004008
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004008" ON "GRC_WORKFLOW"."ACT_RU_JOB" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004085
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004085" ON "GRC_WORKFLOW"."ACT_ID_MEMBERSHIP" ("USER_ID_", "GROUP_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_MEMB_GROUP
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_MEMB_GROUP" ON "GRC_WORKFLOW"."ACT_ID_MEMBERSHIP" ("GROUP_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_MEMB_USER
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_MEMB_USER" ON "GRC_WORKFLOW"."ACT_ID_MEMBERSHIP" ("USER_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_EXE_PROCDEF
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_EXE_PROCDEF" ON "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("PROC_DEF_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_EXEC_BUSKEY
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_EXEC_BUSKEY" ON "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("BUSINESS_KEY_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_EXE_PROCINST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_EXE_PROCINST" ON "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("PROC_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_EXE_PARENT
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_EXE_PARENT" ON "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("PARENT_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_EXE_SUPER
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_EXE_SUPER" ON "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("SUPER_EXEC_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004004
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004004" ON "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C003997
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C003997" ON "GRC_WORKFLOW"."ACT_RE_DEPLOYMENT" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004086
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004086" ON "GRC_WORKFLOW"."ACT_ID_USER" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_ACT_INST_START
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_ACT_INST_START" ON "GRC_WORKFLOW"."ACT_HI_ACTINST" ("START_TIME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_ACT_INST_END
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_ACT_INST_END" ON "GRC_WORKFLOW"."ACT_HI_ACTINST" ("END_TIME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_ACT_INST_PROCINST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_ACT_INST_PROCINST" ON "GRC_WORKFLOW"."ACT_HI_ACTINST" ("PROC_INST_ID_", "ACT_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_ACT_INST_EXEC
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_ACT_INST_EXEC" ON "GRC_WORKFLOW"."ACT_HI_ACTINST" ("EXECUTION_ID_", "ACT_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004066
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004066" ON "GRC_WORKFLOW"."ACT_HI_ACTINST" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_PROCDEF_INFO_JSON
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_PROCDEF_INFO_JSON" ON "GRC_WORKFLOW"."ACT_PROCDEF_INFO" ("INFO_JSON_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_PROCDEF_INFO_PROC
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_PROCDEF_INFO_PROC" ON "GRC_WORKFLOW"."ACT_PROCDEF_INFO" ("PROC_DEF_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004029
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004029" ON "GRC_WORKFLOW"."ACT_PROCDEF_INFO" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004087
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004087" ON "GRC_WORKFLOW"."ACT_ID_INFO" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_EVENT_SUBSCR
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_EVENT_SUBSCR" ON "GRC_WORKFLOW"."ACT_RU_EVENT_SUBSCR" ("EXECUTION_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004024
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004024" ON "GRC_WORKFLOW"."ACT_RU_EVENT_SUBSCR" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_EVENT_SUBSCR_CONFIG_
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_EVENT_SUBSCR_CONFIG_" ON "GRC_WORKFLOW"."ACT_RU_EVENT_SUBSCR" ("CONFIGURATION_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004082
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004082" ON "GRC_WORKFLOW"."ACT_HI_ATTACHMENT" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_PRO_INST_END
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_PRO_INST_END" ON "GRC_WORKFLOW"."ACT_HI_PROCINST" ("END_TIME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_PRO_I_BUSKEY
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_PRO_I_BUSKEY" ON "GRC_WORKFLOW"."ACT_HI_PROCINST" ("BUSINESS_KEY_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004057
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004057" ON "GRC_WORKFLOW"."ACT_HI_PROCINST" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004058
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004058" ON "GRC_WORKFLOW"."ACT_HI_PROCINST" ("PROC_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_DETAIL_PROC_INST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_DETAIL_PROC_INST" ON "GRC_WORKFLOW"."ACT_HI_DETAIL" ("PROC_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_DETAIL_ACT_INST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_DETAIL_ACT_INST" ON "GRC_WORKFLOW"."ACT_HI_DETAIL" ("ACT_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_DETAIL_TIME
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_DETAIL_TIME" ON "GRC_WORKFLOW"."ACT_HI_DETAIL" ("TIME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_DETAIL_NAME
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_DETAIL_NAME" ON "GRC_WORKFLOW"."ACT_HI_DETAIL" ("NAME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_DETAIL_TASK_ID
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_DETAIL_TASK_ID" ON "GRC_WORKFLOW"."ACT_HI_DETAIL" ("TASK_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004077
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004077" ON "GRC_WORKFLOW"."ACT_HI_DETAIL" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004016
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004016" ON "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_IDENT_LNK_USER
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_IDENT_LNK_USER" ON "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ("USER_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_IDENT_LNK_GROUP
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_IDENT_LNK_GROUP" ON "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ("GROUP_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_TSKASS_TASK
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_TSKASS_TASK" ON "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ("TASK_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_ATHRZ_PROCEDEF
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_ATHRZ_PROCEDEF" ON "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ("PROC_DEF_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_IDL_PROCINST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_IDL_PROCINST" ON "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ("PROC_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_BYTEAR_DEPL
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_BYTEAR_DEPL" ON "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ("DEPLOYMENT_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C003996
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C003996" ON "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004083
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004083" ON "GRC_WORKFLOW"."ACT_HI_IDENTITYLINK" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_IDENT_LNK_USER
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_IDENT_LNK_USER" ON "GRC_WORKFLOW"."ACT_HI_IDENTITYLINK" ("USER_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_IDENT_LNK_TASK
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_IDENT_LNK_TASK" ON "GRC_WORKFLOW"."ACT_HI_IDENTITYLINK" ("TASK_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_IDENT_LNK_PROCINST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_IDENT_LNK_PROCINST" ON "GRC_WORKFLOW"."ACT_HI_IDENTITYLINK" ("PROC_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_VAR_BYTEARRAY
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_VAR_BYTEARRAY" ON "GRC_WORKFLOW"."ACT_RU_VARIABLE" ("BYTEARRAY_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004020
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004020" ON "GRC_WORKFLOW"."ACT_RU_VARIABLE" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_VARIABLE_TASK_ID
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_VARIABLE_TASK_ID" ON "GRC_WORKFLOW"."ACT_RU_VARIABLE" ("TASK_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_VAR_EXE
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_VAR_EXE" ON "GRC_WORKFLOW"."ACT_RU_VARIABLE" ("EXECUTION_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_VAR_PROCINST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_VAR_PROCINST" ON "GRC_WORKFLOW"."ACT_RU_VARIABLE" ("PROC_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_UNIQ_PROCDEF
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."ACT_UNIQ_PROCDEF" ON "GRC_WORKFLOW"."ACT_RE_PROCDEF" ("KEY_", "VERSION_", "TENANT_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004014
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004014" ON "GRC_WORKFLOW"."ACT_RE_PROCDEF" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_MODEL_SOURCE_EXTRA
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_MODEL_SOURCE_EXTRA" ON "GRC_WORKFLOW"."ACT_RE_MODEL" ("EDITOR_SOURCE_EXTRA_VALUE_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_MODEL_DEPLOYMENT
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_MODEL_DEPLOYMENT" ON "GRC_WORKFLOW"."ACT_RE_MODEL" ("DEPLOYMENT_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_MODEL_SOURCE
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_MODEL_SOURCE" ON "GRC_WORKFLOW"."ACT_RE_MODEL" ("EDITOR_SOURCE_VALUE_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C003999
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C003999" ON "GRC_WORKFLOW"."ACT_RE_MODEL" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_PROCVAR_PROC_INST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_PROCVAR_PROC_INST" ON "GRC_WORKFLOW"."ACT_HI_VARINST" ("PROC_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_PROCVAR_NAME_TYPE
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_PROCVAR_NAME_TYPE" ON "GRC_WORKFLOW"."ACT_HI_VARINST" ("NAME_", "VAR_TYPE_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_PROCVAR_TASK_ID
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_PROCVAR_TASK_ID" ON "GRC_WORKFLOW"."ACT_HI_VARINST" ("TASK_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004072
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004072" ON "GRC_WORKFLOW"."ACT_HI_VARINST" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004080
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004080" ON "GRC_WORKFLOW"."ACT_HI_COMMENT" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index ACT_IDX_HI_TASK_INST_PROCINST
--------------------------------------------------------

  CREATE INDEX "GRC_WORKFLOW"."ACT_IDX_HI_TASK_INST_PROCINST" ON "GRC_WORKFLOW"."ACT_HI_TASKINST" ("PROC_INST_ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004069
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004069" ON "GRC_WORKFLOW"."ACT_HI_TASKINST" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C003994
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C003994" ON "GRC_WORKFLOW"."ACT_GE_PROPERTY" ("NAME_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C004084
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRC_WORKFLOW"."SYS_C004084" ON "GRC_WORKFLOW"."ACT_ID_GROUP" ("ID_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA" ;
--------------------------------------------------------
--  Constraints for Table ACT_EVT_LOG
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_EVT_LOG" MODIFY ("TIME_STAMP_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_EVT_LOG" ADD PRIMARY KEY ("LOG_NR_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_RU_TASK
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_TASK" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_RU_JOB
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_JOB" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_JOB" MODIFY ("TYPE_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_JOB" ADD CHECK (EXCLUSIVE_ IN (1,0)) ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_JOB" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_ID_MEMBERSHIP
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_ID_MEMBERSHIP" ADD PRIMARY KEY ("USER_ID_", "GROUP_ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_RU_EXECUTION
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" ADD CHECK (IS_ACTIVE_ IN (1,0)) ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" ADD CHECK (IS_CONCURRENT_ IN (1,0)) ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" ADD CHECK (IS_SCOPE_ IN (1,0)) ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" ADD CHECK (IS_EVENT_SCOPE_ IN (1,0)) ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_RE_DEPLOYMENT
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_DEPLOYMENT" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_ID_USER
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_ID_USER" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_HI_ACTINST
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ACTINST" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ACTINST" MODIFY ("PROC_DEF_ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ACTINST" MODIFY ("PROC_INST_ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ACTINST" MODIFY ("EXECUTION_ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ACTINST" MODIFY ("ACT_ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ACTINST" MODIFY ("ACT_TYPE_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ACTINST" MODIFY ("START_TIME_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ACTINST" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_PROCDEF_INFO
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_PROCDEF_INFO" ADD CONSTRAINT "ACT_UNIQ_INFO_PROCDEF" UNIQUE ("PROC_DEF_ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_PROCDEF_INFO" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_PROCDEF_INFO" MODIFY ("PROC_DEF_ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_PROCDEF_INFO" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_ID_INFO
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_ID_INFO" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_RU_EVENT_SUBSCR
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EVENT_SUBSCR" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EVENT_SUBSCR" MODIFY ("EVENT_TYPE_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EVENT_SUBSCR" MODIFY ("CREATED_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EVENT_SUBSCR" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_HI_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ATTACHMENT" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_ATTACHMENT" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_HI_PROCINST
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_PROCINST" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_PROCINST" MODIFY ("PROC_INST_ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_PROCINST" MODIFY ("PROC_DEF_ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_PROCINST" MODIFY ("START_TIME_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_PROCINST" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_PROCINST" ADD UNIQUE ("PROC_INST_ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_HI_DETAIL
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_DETAIL" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_DETAIL" MODIFY ("TYPE_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_DETAIL" MODIFY ("NAME_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_DETAIL" MODIFY ("TIME_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_DETAIL" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_RU_IDENTITYLINK
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_GE_BYTEARRAY
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ADD CHECK (GENERATED_ IN (1,0)) ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_HI_IDENTITYLINK
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_IDENTITYLINK" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_RU_VARIABLE
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_VARIABLE" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_VARIABLE" MODIFY ("TYPE_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_VARIABLE" MODIFY ("NAME_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_VARIABLE" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_RE_PROCDEF
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_PROCDEF" ADD CONSTRAINT "ACT_UNIQ_PROCDEF" UNIQUE ("KEY_", "VERSION_", "TENANT_ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_PROCDEF" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_PROCDEF" MODIFY ("KEY_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_PROCDEF" MODIFY ("VERSION_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_PROCDEF" ADD CHECK (HAS_START_FORM_KEY_ IN (1,0)) ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_PROCDEF" ADD CHECK (HAS_GRAPHICAL_NOTATION_ IN (1,0)) ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_PROCDEF" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_RE_MODEL
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_MODEL" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_MODEL" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_HI_VARINST
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_VARINST" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_VARINST" MODIFY ("NAME_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_VARINST" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_HI_COMMENT
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_COMMENT" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_COMMENT" MODIFY ("TIME_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_COMMENT" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_HI_TASKINST
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_TASKINST" MODIFY ("ID_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_TASKINST" MODIFY ("START_TIME_" NOT NULL ENABLE);
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_HI_TASKINST" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_GE_PROPERTY
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_GE_PROPERTY" ADD PRIMARY KEY ("NAME_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACT_ID_GROUP
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_ID_GROUP" ADD PRIMARY KEY ("ID_")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRC_WORKFLOW_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_RU_TASK
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_TASK" ADD CONSTRAINT "ACT_FK_TASK_EXE" FOREIGN KEY ("EXECUTION_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_TASK" ADD CONSTRAINT "ACT_FK_TASK_PROCDEF" FOREIGN KEY ("PROC_DEF_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RE_PROCDEF" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_TASK" ADD CONSTRAINT "ACT_FK_TASK_PROCINST" FOREIGN KEY ("PROC_INST_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_RU_JOB
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_JOB" ADD CONSTRAINT "ACT_FK_JOB_EXCEPTION" FOREIGN KEY ("EXCEPTION_STACK_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_ID_MEMBERSHIP
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_ID_MEMBERSHIP" ADD CONSTRAINT "ACT_FK_MEMB_GROUP" FOREIGN KEY ("GROUP_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_ID_GROUP" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_ID_MEMBERSHIP" ADD CONSTRAINT "ACT_FK_MEMB_USER" FOREIGN KEY ("USER_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_ID_USER" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_RU_EXECUTION
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" ADD CONSTRAINT "ACT_FK_EXE_PARENT" FOREIGN KEY ("PARENT_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" ADD CONSTRAINT "ACT_FK_EXE_PROCDEF" FOREIGN KEY ("PROC_DEF_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RE_PROCDEF" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" ADD CONSTRAINT "ACT_FK_EXE_PROCINST" FOREIGN KEY ("PROC_INST_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EXECUTION" ADD CONSTRAINT "ACT_FK_EXE_SUPER" FOREIGN KEY ("SUPER_EXEC_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_PROCDEF_INFO
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_PROCDEF_INFO" ADD CONSTRAINT "ACT_FK_INFO_JSON_BA" FOREIGN KEY ("INFO_JSON_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_PROCDEF_INFO" ADD CONSTRAINT "ACT_FK_INFO_PROCDEF" FOREIGN KEY ("PROC_DEF_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RE_PROCDEF" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_RU_EVENT_SUBSCR
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_EVENT_SUBSCR" ADD CONSTRAINT "ACT_FK_EVENT_EXEC" FOREIGN KEY ("EXECUTION_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_RU_IDENTITYLINK
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ADD CONSTRAINT "ACT_FK_ATHRZ_PROCEDEF" FOREIGN KEY ("PROC_DEF_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RE_PROCDEF" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ADD CONSTRAINT "ACT_FK_IDL_PROCINST" FOREIGN KEY ("PROC_INST_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_IDENTITYLINK" ADD CONSTRAINT "ACT_FK_TSKASS_TASK" FOREIGN KEY ("TASK_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_TASK" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_GE_BYTEARRAY
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ADD CONSTRAINT "ACT_FK_BYTEARR_DEPL" FOREIGN KEY ("DEPLOYMENT_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RE_DEPLOYMENT" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_RU_VARIABLE
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_VARIABLE" ADD CONSTRAINT "ACT_FK_VAR_BYTEARRAY" FOREIGN KEY ("BYTEARRAY_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_VARIABLE" ADD CONSTRAINT "ACT_FK_VAR_EXE" FOREIGN KEY ("EXECUTION_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RU_VARIABLE" ADD CONSTRAINT "ACT_FK_VAR_PROCINST" FOREIGN KEY ("PROC_INST_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RU_EXECUTION" ("ID_") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_RE_MODEL
--------------------------------------------------------

  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_MODEL" ADD CONSTRAINT "ACT_FK_MODEL_DEPLOYMENT" FOREIGN KEY ("DEPLOYMENT_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_RE_DEPLOYMENT" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_MODEL" ADD CONSTRAINT "ACT_FK_MODEL_SOURCE" FOREIGN KEY ("EDITOR_SOURCE_VALUE_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ("ID_") ENABLE;
 
  ALTER TABLE "GRC_WORKFLOW"."ACT_RE_MODEL" ADD CONSTRAINT "ACT_FK_MODEL_SOURCE_EXTRA" FOREIGN KEY ("EDITOR_SOURCE_EXTRA_VALUE_ID_")
      REFERENCES "GRC_WORKFLOW"."ACT_GE_BYTEARRAY" ("ID_") ENABLE;