//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.14 at 02:16:36 PM CST 
//


package com.thomsonreuters.grc.workflow.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionType", propOrder = {
    "outcomeList"
})
public class ActionType {

    protected OutcomeList outcomeList;
    
    public ActionType() {
    	
    }

    public OutcomeList getOutcomeList() {
        return outcomeList;
    }

    public void setOutcomeList(OutcomeList outcomeList) {
        this.outcomeList = outcomeList;
    }
    

}
